name: EZG-BANK
version: '1.0.0'
main: nl.samskeee.ezgbank.Main
api-version: '1.15'
author: Itsdevsam / __DieEneRus__
depend: [Vault]
softdepend: [WorldGuard, WorldEdit]
commands:
  bankoverval:
    description: Start een bankoverval of controleer status.
    usage: /<command> [start|status]
  bankadmin:
    description: Admin commands voor banken (add/remove/list).
    usage: /bankadmin <subcommand>
permissions:
  ezgbank.admin:
    description: Beheer banken
    default: op